# Generated by Django 2.1 on 2018-08-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calisan',
            fields=[
                ('calisan_id', models.AutoField(primary_key=True, serialize=False)),
                ('calisan_adi', models.CharField(max_length=10)),
                ('calisan_soyadi', models.CharField(max_length=10)),
                ('calisan_yetki', models.CharField(max_length=5)),
                ('calisan_sifre', models.CharField(max_length=10)),
                ('calisan_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gorev',
            fields=[
                ('gorev_id', models.AutoField(primary_key=True, serialize=False)),
                ('gorev_adi', models.CharField(max_length=10)),
                ('gorev_teslim_tarih', models.DateField(verbose_name='Son Teslim Tarihi')),
                ('gorev_durum', models.BooleanField(default=False)),
                ('gorev_alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_alan', to='takip.Calisan')),
                ('gorev_veren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_veren', to='takip.Calisan')),
            ],
        ),
        migrations.CreateModel(
            name='Proje',
            fields=[
                ('proje_id', models.AutoField(primary_key=True, serialize=False)),
                ('proje_adi', models.CharField(max_length=50)),
                ('proje_baslama_tarih', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('proje_teslim_tarih', models.DateField(verbose_name='Bitiş Tarihi')),
            ],
        ),
        migrations.AddField(
            model_name='gorev',
            name='proje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takip.Proje'),
        ),
    ]
